version: "3.7"
services: 
    micro_01:
        build: 
            args: 
                user: micro_01      #Will be used in Dockerfile
                uid: 1000           #Will be used in Dockerfile
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        #command: "php artisan serve"   #This could be done but is not a good practice
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        