version: "3.7"
services: 
    #Micro service 01
    micro_01:
        build: 
            args: 
                user: micro_01      #Will be used in Dockerfile
                uid: 1000           #Will be used in Dockerfile
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        #command: "php artisan serve"   #This could be done but is not a good practice
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_01
        networks:
            - microservices

    #nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            # - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d     #if using apache ./docker/apache:/etc/apache2/sites-available/, create the conf file
        networks:
            - microservices

    #mysql
    db_micro_01:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/db_data:/var/lib/mysql      #Database will be saved in this folder... DON'T FORGET to add it in .gitignore
        networks:
            - microservices

    #queue micro 01
    queue_micro_01:
        build: 
            args: 
                user: micro_01      #Will be used in Dockerfile
                uid: 1000           #Will be used in Dockerfile
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on: 
            - redis_micro_01
        networks:
            - microservices

    #redis
    redis_micro_01:
        image: redis:latest
        networks:
            - microservices

    
networks:
    microservices:
        driver: bridge    

        